[global]
strategy = 'packets'
log_level = 'debug'
filter = true
clear_packets_interval = 100

[telemetry]
enabled = false
host = '0.0.0.0'
port = 3001

[[chains]]
id='iov-mainnet-ibc'
rpc_addr='http://10.10.51.23:26657'
grpc_addr='http://10.10.51.23:9090'
websocket_addr='ws://10.10.51.23:26657/websocket'
rpc_timeout='8s'
account_prefix='star'
key_name='iov-wallet'
store_prefix='ibc'
gas_price = { price = 0.02, denom = 'uiov' }
max_gas=1100000
max_msg_num=15
clock_drift='7200s'
trusting_period='14days'

[chains.packet_filter]
policy = 'allow'
list = [['transfer', 'channel-2']]

[chains.trust_threshold]
numerator='1'
denominator='3'

[[chains]]
id='osmosis-1'
rpc_addr='http://10.10.51.151:26657'
grpc_addr='http://10.10.51.151:9090'
websocket_addr='ws://10.10.51.151:26657/websocket'
#rpc_addr='http://144.217.79.221:26657'
#grpc_addr='http://144.217.79.221:9090'
#websocket_addr='ws://144.217.79.221:26657/websocket'
rpc_timeout='8s'
account_prefix='osmo'
key_name='hw-osmosis'
store_prefix='ibc'
gas_price = { price = 0, denom = 'uosmo' }
max_gas=4000000
max_msg_num=8
clock_drift='7200s'
trusting_period='14days'

[chains.packet_filter]
policy = 'allow'
list = [['transfer', 'channel-15']]

[chains.trust_threshold]
numerator='1'
denominator='3'
