[global]
strategy = 'packets'
log_level = 'error'

[telemetry]
enabled = true
host = '127.0.0.1'
port = 3001

[[chains]]
id='cosmoshub-4'
rpc_addr='http://10.10.51.251:26657'
grpc_addr='http://10.10.51.251:9090'
websocket_addr='ws://10.10.51.251:26657/websocket'
rpc_timeout='12s'
account_prefix='cosmos'
key_name='hw-gaiad'
store_prefix='ibc'
gas_price = { price = 0.01, denom = 'uatom' }
max_gas=1100000
max_msg_num=15
clock_drift='7200s'
trusting_period='14days'

[chains.trust_threshold]
numerator='1'
denominator='3'

[[chains]]
id='irishub-1'
rpc_addr='http://10.10.51.66:26657'
grpc_addr='http://10.10.51.66:9090'
websocket_addr='ws://10.10.51.66:26657/websocket'
rpc_timeout='12s'
account_prefix='iaa'
key_name='hw-irishub'
store_prefix='ibc'
gas_price = { price = 0.01, denom = 'uiris' }
max_gas=800000
clock_drift='7200s'
trusting_period='14days'

[chains.trust_threshold]
numerator='1'
denominator='3'

[[chains]]
id='core-1'
rpc_addr='http://10.10.51.40:26657'
grpc_addr='http://10.10.51.40:9090'
websocket_addr='ws://10.10.51.40:26657/websocket'
rpc_timeout='12s'
account_prefix='persistence'
key_name='hw-persistenceOne'
store_prefix='ibc'
gas_price = { price = 0.01, denom = 'uxprt' }
max_gas=800000
clock_drift='7200s'
trusting_period='14days'

[chains.trust_threshold]
numerator='1'
denominator='3'

[[chains]]
id='sentinelhub-2'
rpc_addr='http://10.10.51.31:26657'
grpc_addr='http://10.10.51.31:9090'
websocket_addr='ws://10.10.51.31:26657/websocket'
rpc_timeout='12s'
account_prefix='sent'
key_name='hw-sentinel'
store_prefix='ibc'
gas_price = { price = 0.01, denom = 'udvpn' }
max_gas=1000000
max_msg_num=15
clock_drift='7200s'
trusting_period='14days'

[chains.trust_threshold]
numerator='1'
denominator='3'

[[chains]]
id='crypto-org-chain-mainnet-1'
rpc_addr='http://10.10.51.76:26657'
grpc_addr='http://10.10.51.76:9090'
websocket_addr='ws://10.10.51.76:26657/websocket'
rpc_timeout='12s'
account_prefix='cro'
key_name='hw-cryptoCom'
store_prefix='ibc'
gas_price = { price = 0.01, denom = 'basecro' }
max_gas=1200000
max_msg_num=15
clock_drift='7200s'
trusting_period='14days'

[chains.trust_threshold]
numerator='1'
denominator='3'

[[chains]]
id='osmosis-1'
rpc_addr='http://10.10.51.151:26657'
grpc_addr='http://10.10.51.151:9090'
websocket_addr='ws://10.10.51.151:26657/websocket'
rpc_timeout='12s'
account_prefix='osmo'
key_name='hw-osmosis'
store_prefix='ibc'
gas_price = { price = 0, denom = 'uosmo' }
max_gas=3000000
max_msg_num=15
clock_drift='7200s'
trusting_period='14days'

[chains.trust_threshold]
numerator='1'
denominator='3'

[[chains]]
id='akashnet-2'
rpc_addr='http://10.10.51.69:26657'
grpc_addr='http://10.10.51.69:9090'
websocket_addr='ws://10.10.51.69:26657/websocket'
rpc_timeout='12s'
account_prefix='akash'
key_name='hw-akash'
store_prefix='ibc'
gas_price = { price = 0.01, denom = 'uakt' }
max_gas=800000
clock_drift='7200s'
trusting_period='14days'

[chains.trust_threshold]
numerator='1'
denominator='3'

[[chains]]
id='regen-1'
rpc_addr='http://10.10.51.245:26657'
grpc_addr='http://10.10.51.245:9090'
websocket_addr='ws://10.10.51.245:26657/websocket'
rpc_timeout='12s'
account_prefix='regen'
key_name='hw-regen'
store_prefix='ibc'
gas_price = { price = 0.01, denom = 'uregen' }
max_gas=800000
max_msg_num=15
clock_drift='7200s'
trusting_period='14days'

[chains.trust_threshold]
numerator='1'
denominator='3'
