positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://{{ key "loki-addr" }}/loki/api/v1/push

scrape_configs:
  - job_name: syslog
    syslog:
      listen_address: {{ key "listen-address" }}
      labels:
        job: 'syslog'
    relabel_configs:
      - source_labels: ['__syslog_message_hostname']
        target_label: 'host'