[global]
log_level = 'debug'

[mode]
[mode.clients]
enabled = true
refresh = true
misbehaviour = false

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
filter = true
tx_confirmation = false


[rest]
enabled = true
host = '0.0.0.0'
port = 3000


[[chains]]
id = 'cosmoshub-4'

rpc_addr = 'http://cosmoshub1:26657'
grpc_addr = 'http://cosmoshub1:9090'

#rpc_addr = 'http://10.10.10.103:26670' # archive node
#grpc_addr = 'http://10.10.10.103:26672'

websocket_addr = 'ws://cosmoshub1:26657/websocket'
rpc_timeout = '8s'
account_prefix = 'cosmos'
key_name = 'aw1'
store_prefix = 'ibc'
memo_prefix = 'Connect the Interchain. Stake with Cephalopod 🐙'
gas_price  =  { price  =  0.01, denom  =  'uatom' }
max_gas = 19000000
max_msg_num = 15
max_tx_size = 180000
clock_drift = '7200s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
packet_filter = { policy = 'allow', list = [['transfer', 'channel-141']]}



[[chains]]
id = 'akashnet-2'

rpc_addr = 'http://akashnet0:26657'
grpc_addr = 'http://akashnet0:9090'

#rpc_addr = 'http://10.10.10.103:26640' # archive node
#grpc_addr = 'http://10.10.10.103:26642'

websocket_addr = 'ws://akashnet0:26657/websocket'
rpc_timeout = '8s'
account_prefix = 'akash'
key_name = 'aw1'
store_prefix = 'ibc'
memo_prefix = 'Connect the Interchain. Stake with Cephalopod 🐙'
gas_price  =  { price  =  0.001, denom  =  'uakt' }
max_gas = 1000000
clock_drift = '7200s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
packet_filter = { policy = 'allow', list = [['transfer', 'channel-9']]}


[[chains]]
id = 'sentinelhub-2'
rpc_addr = 'http://10.10.51.47:26657' # sentinelhub0
grpc_addr = 'http://10.10.51.47:9090'
websocket_addr = 'ws://10.10.51.47:26657/websocket'
rpc_timeout = '8s'
account_prefix = 'sent'
key_name = 'aw1'
store_prefix = 'ibc'
memo_prefix = 'Connect the Interchain. Stake with Cephalopod 🐙'
gas_price  =  { price  =  0.01, denom  =  'udvpn' }
max_gas = 1000000
max_msg_num = 15
clock_drift = '7200s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
packet_filter = { policy = 'allow', list = [['transfer', 'channel-0']]}


[[chains]]
id = 'crypto-org-chain-mainnet-1'
rpc_addr = 'http://10.10.51.95:26657' # crypto1
grpc_addr = 'http://10.10.51.95:9090'
websocket_addr = 'ws://10.10.51.95:26657/websocket'
rpc_timeout = '8s'
account_prefix = 'cro'
key_name = 'aw1'
store_prefix = 'ibc'
memo_prefix = 'Connect the Interchain. Stake with Cephalopod 🐙'
gas_price  =  { price  =  0.1, denom  =  'basecro' }
max_gas = 1200000
max_msg_num = 15
max_tx_size = 450000
clock_drift = '7200s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
packet_filter = { policy = 'allow', list = [['transfer', 'channel-10']]}


[[chains]]
id = 'regen-1'
#rpc_addr = 'http://regen1:26657'
#grpc_addr = 'http://regen1:9090'

rpc_addr = 'http://10.10.10.103:26680'
grpc_addr = 'http://10.10.10.103:26682'

websocket_addr = 'ws://regen1:26657/websocket'
rpc_timeout = '8s'
account_prefix = 'regen'
key_name = 'aw2'
store_prefix = 'ibc'
memo_prefix = 'Connect the Interchain. Stake with Cephalopod 🐙'
gas_price  =  { price  =  0.1, denom  =  'uregen' }
max_gas = 800000
max_msg_num = 15
max_tx_size = 180000
clock_drift = '7200s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
packet_filter = { policy = 'allow', list = [['transfer', 'channel-1']]}


[[chains]]
id = 'core-1'
rpc_addr = 'http://10.10.51.84:26657' # core0
grpc_addr = 'http://10.10.51.84:9090'
websocket_addr = 'ws://10.10.51.84:26657/websocket'
rpc_timeout = '8s'
account_prefix = 'persistence'
key_name = 'aw1'
store_prefix = 'ibc'
memo_prefix = 'Connect the Interchain. Stake with Cephalopod 🐙'
gas_price  =  { price  =  0.001, denom  =  'uxprt' }
max_gas = 2000000
max_msg_num = 15
max_tx_size = 180000
clock_drift = '7200s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
packet_filter = { policy = 'allow', list = [['transfer', 'channel-6']]}


[[chains]]
id = 'irishub-1'
rpc_addr = 'http://irishub0:26657' # irishub0
grpc_addr = 'http://irishub0:9090'
websocket_addr = 'ws://irishub0:26657/websocket'
rpc_timeout = '8s'
account_prefix = 'iaa'
key_name = 'aw1'
store_prefix = 'ibc'
memo_prefix = 'Connect the Interchain. Stake with Cephalopod 🐙'
gas_price  =  { price  =  0.01, denom  =  'uiris' }
max_gas = 5000000
max_msg_num = 15
max_tx_size = 1800000
clock_drift = '7200s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
packet_filter = { policy = 'allow', list = [['transfer', 'channel-3']]}


[[chains]]
id = 'iov-mainnet-ibc'
rpc_addr = 'http://iov0:26657'
grpc_addr = 'http://iov0:9090'
websocket_addr = 'ws://iov0:26657/websocket'
rpc_timeout = '8s'
account_prefix = 'star'
key_name = 'aw1'
store_prefix = 'ibc'
memo_prefix = 'Connect the Interchain. Stake with Cephalopod 🐙'
gas_price  =  { price  =  0.1, denom  =  'uiov' }
max_gas = 5000000
max_msg_num = 15
max_tx_size = 450000
clock_drift = '7200s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
packet_filter = { policy = 'allow', list = [['transfer', 'channel-2']]}


[[chains]]
id = 'impacthub-3'
rpc_addr = 'http://impacthub0:26657'
grpc_addr = 'http://impacthub0:9090'
websocket_addr = 'ws://impacthub0:26657/websocket'
rpc_timeout = '8s'
account_prefix = 'ixo'
key_name = 'aw1'
store_prefix = 'ibc'
memo_prefix = 'Connect the Interchain. Stake with Cephalopod 🐙'
gas_price = { price = 0.01, denom = 'uixo' }
max_gas = 5000000
max_msg_num = 15
max_tx_size = 180000
clock_drift = '7200s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
packet_filter = { policy = 'allow', list = [['transfer', 'channel-4']]}


[[chains]]
id = 'juno-1'
rpc_addr = 'http://juno0.cec:26657'
grpc_addr = 'http://juno0.cec:9090'
websocket_addr = 'ws://juno0.cec:26657/websocket'
rpc_timeout = '8s'
account_prefix = 'juno'
key_name = 'aw2'
store_prefix = 'ibc'
memo_prefix = 'Connect the Interchain. Stake with Cephalopod 🐙'
gas_price  =  { price  =  0.001, denom  =  'ujuno' }
max_gas = 5000000
max_msg_num = 15
max_tx_size = 450000
clock_drift = '7200s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
packet_filter = { policy = 'allow', list = [['transfer', 'channel-0']]}


[[chains]]
id = 'osmosis-1'

#rpc_addr = 'http://osmosis1:26657'
#grpc_addr = 'http://osmosis1:9090'

rpc_addr = 'http://10.10.10.103:26700' # node: osmosis-archive-node
grpc_addr = 'http://10.10.10.103:26702'

websocket_addr = 'ws://osmosis0:26657/websocket'
rpc_timeout = '8s'
account_prefix = 'osmo'
key_name = 'aw1'
store_prefix = 'ibc'
memo_prefix = 'Connect the Interchain. Stake with Cephalopod 🐙'
gas_price  =  { price  =  0.1, denom  =  'uosmo' }
max_gas = 19000000
max_msg_num = 8
clock_drift = '7200s'
trusting_period = '10days'
trust_threshold = { numerator = '1', denominator = '3' }
packet_filter = { policy = 'allow', list = [['transfer', 'channel-1'],['transfer', 'channel-2'],['transfer', 'channel-5'],['transfer', 'channel-8'],['transfer', 'channel-6'],['transfer', 'channel-15'],['transfer', 'channel-4'],['transfer', 'channel-0'],['transfer', 'channel-42'],['transfer','channel-38']]}
