[global]
strategy = 'packets'
log_level = 'debug'
filter = true
clear_packets_interval = 100

[[chains]]
id='cosmoshub-4'
rpc_addr='http://144.217.252.148:26657'
grpc_addr='http://144.217.252.148:9090'
websocket_addr='ws://144.217.252.148:26657/websocket'
rpc_timeout='20s'
account_prefix='cosmos'
key_name='cosmoshub-troubleshooting'
store_prefix='ibc'
gas_price = { price = 0.02, denom = 'uatom' }
max_gas=1100000
max_msg_num=15
clock_drift='7200s'
trusting_period='14days'

[chains.packet_filter]
policy = 'allow'
list = [['transfer', 'channel-141']]

[chains.trust_threshold]
numerator='1'
denominator='3'

[[chains]]
id='irishub-1'
rpc_addr='http://10.10.51.66:26657'
grpc_addr='http://10.10.51.66:9090'
websocket_addr='ws://10.10.51.66:26657/websocket'
rpc_timeout='20s'
account_prefix='iaa'
key_name='irishub-troubleshooting'
store_prefix='ibc'
gas_price = { price = 0.01, denom = 'uiris' }
max_gas=800000
clock_drift='7200s'
trusting_period='14days'

[chains.packet_filter]
policy = 'allow'
list = [['transfer', 'channel-3']]

[chains.trust_threshold]
numerator='1'
denominator='3'

[[chains]]
id='core-1'
rpc_addr='http://10.10.51.40:26657'
grpc_addr='http://10.10.51.40:9090'
websocket_addr='ws://10.10.51.40:26657/websocket'
rpc_timeout='20s'
account_prefix='persistence'
key_name='persistenceOne-troubleshooting'
store_prefix='ibc'
gas_price = { price = 0.01, denom = 'uxprt' }
max_gas=1000000
clock_drift='7200s'
trusting_period='14days'

[chains.packet_filter]
policy = 'allow'
list = [['transfer', 'channel-6']]

[chains.trust_threshold]
numerator='1'
denominator='3'

[[chains]]
id='sentinelhub-2'
rpc_addr='http://10.10.51.31:26657'
grpc_addr='http://10.10.51.31:9090'
websocket_addr='ws://10.10.51.31:26657/websocket'
rpc_timeout='20s'
account_prefix='sent'
key_name='sentinel-troubleshooting'
store_prefix='ibc'
gas_price = { price = 0.01, denom = 'udvpn' }
max_gas=1000000
max_msg_num=15
clock_drift='7200s'
trusting_period='14days'

[chains.packet_filter]
policy = 'allow'
list = [['transfer', 'channel-0']]

[chains.trust_threshold]
numerator='1'
denominator='3'

[[chains]]
id='crypto-org-chain-mainnet-1'
rpc_addr='http://10.10.51.76:26657'
grpc_addr='http://10.10.51.76:9090'
websocket_addr='ws://10.10.51.76:26657/websocket'
rpc_timeout='20s'
account_prefix='cro'
key_name='cryptoCom-troubleshooting'
store_prefix='ibc'
gas_price = { price = 0.01, denom = 'basecro' }
max_gas=1200000
max_msg_num=15
clock_drift='7200s'
trusting_period='14days'

[chains.packet_filter]
policy = 'allow'
list = [['transfer', 'channel-10']]

[chains.trust_threshold]
numerator='1'
denominator='3'

[[chains]]
id='osmosis-1'
rpc_addr='http://144.217.79.221:26657'
grpc_addr='http://144.217.79.221:9090'
websocket_addr='ws://144.217.79.221:26657/websocket'
rpc_timeout='20s'
account_prefix='osmo'
key_name='osmosis-troubleshooting'
store_prefix='ibc'
gas_price = { price = 0, denom = 'uosmo' }
max_gas=5000000
max_msg_num=8
clock_drift='7200s'
trusting_period='14days'

[chains.packet_filter]
policy = 'allow'
list = [['transfer', 'channel-1'],['transfer', 'channel-0'],['transfer', 'channel-2'],['transfer', 'channel-4'],['transfer', 'channel-5'],['transfer', 'channel-6'],['transfer', 'channel-8'],['transfer', 'channel-15']]

[chains.trust_threshold]
numerator='1'
denominator='3'

[[chains]]
id='akashnet-2'
rpc_addr='http://10.10.51.69:26657'
grpc_addr='http://10.10.51.69:9090'
websocket_addr='ws://10.10.51.69:26657/websocket'
rpc_timeout='20s'
account_prefix='akash'
key_name='akash-troubleshooting'
store_prefix='ibc'
gas_price = { price = 0.01, denom = 'uakt' }
max_gas=800000
clock_drift='7200s'
trusting_period='14days'

[chains.packet_filter]
policy = 'allow'
list = [['transfer', 'channel-9']]

[chains.trust_threshold]
numerator='1'
denominator='3'

[[chains]]
id='regen-1'
rpc_addr='http://10.10.51.245:26657'
grpc_addr='http://10.10.51.245:9090'
websocket_addr='ws://10.10.51.245:26657/websocket'
rpc_timeout='20s'
account_prefix='regen'
key_name='regen-troubleshooting'
store_prefix='ibc'
gas_price = { price = 0.01, denom = 'uregen' }
max_gas=800000
max_msg_num=15
clock_drift='7200s'
trusting_period='14days'

[chains.packet_filter]
policy = 'allow'
list = [['transfer', 'channel-1']]

[chains.trust_threshold]
numerator='1'
denominator='3'

[[chains]]
id='iov-mainnet-ibc'
rpc_addr='http://10.10.51.23:26657'
grpc_addr='http://10.10.51.23:9090'
websocket_addr='ws://10.10.51.23:26657/websocket'
rpc_timeout='20s'
account_prefix='star'
key_name='iov-troubleshooting'
store_prefix='ibc'
gas_price = { price = 0.02, denom = 'uiov' }
max_gas=1100000
max_msg_num=15
max_tx_size=450000
clock_drift='7200s'
trusting_period='14days'

[chains.packet_filter]
policy = 'allow'
list = [['transfer', 'channel-2']]

[chains.trust_threshold]
numerator='1'
denominator='3'
