[global]
log_level = 'debug'

[mode]
[mode.clients]
enabled = true
refresh = true
misbehaviour = false

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = false


[rest]
enabled = true
host = '0.0.0.0'
port = 3000


[[chains]]
id = 'cosmoshub-4'
rpc_addr = 'http://cosmoshub1:26600'
grpc_addr = 'http://cosmoshub1:26602'
websocket_addr = 'ws://cosmoshub1:26600/websocket'
rpc_timeout = '8s'
account_prefix = 'cosmos'
key_name = 'aw1'
store_prefix = 'ibc'
memo_prefix = 'Connect the Interchain. Stake with Cephalopod 🐙'
gas_price  =  { price  =  0.0001, denom  =  'uatom' }
max_gas = 19000000
max_msg_num = 15
max_tx_size = 180000
clock_drift = '7200s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
packet_filter = { policy = 'allow', list = [['transfer', 'channel-281']]}


[[chains]]
id = 'gravity-bridge-3'
rpc_addr = 'http://gravity0:26600'
grpc_addr = 'http://gravity0:26602'
websocket_addr = 'ws://gravity0:26600/websocket'
rpc_timeout = '8s'
account_prefix = 'gravity'
key_name = 'aw1'
store_prefix = 'ibc'
memo_prefix = 'Connect the Interchain. Stake with Cephalopod 🐙'
gas_price  =  { price  =  0.0001, denom  =  'ugraviton' }
max_gas = 19000000
max_msg_num = 8
clock_drift = '7200s'
trusting_period = '10days'
trust_threshold = { numerator = '1', denominator = '3' }
packet_filter = { policy = 'allow', list = [['transfer', 'channel-17']]}
