[global]
log_level = 'debug'

[mode]
[mode.clients]
enabled = false

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true

[[chains]]
id = 'cosmoshub-4'
rpc_addr = 'http://cosmoshub-archive:26600'
grpc_addr = 'http://cosmoshub-archive:26602'
websocket_addr = 'ws://cosmoshub1:26600/websocket'
rpc_timeout = '8s'
account_prefix = 'cosmos'
key_name = 'aw1'
store_prefix = 'ibc'
memo_prefix = 'Connect the Interchain. Stake with Cephalopod 🐙'
gas_price  =  { price  =  0.0001, denom  =  'uatom' }
max_gas = 3000000
max_msg_num = 15
max_tx_size = 180000
clock_drift = '7200s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }

[[chains]]
id ='akashnet-2'
rpc_addr ='http://10.10.51.16:26630'
grpc_addr ='http://10.10.51.16:26632'
websocket_addr ='ws://akashnet1:26600/websocket'
rpc_timeout ='8s'
account_prefix ='akash'
key_name ='aw1'
store_prefix ='ibc'
memo_prefix = 'Connect the Interchain. Stake with Cephalopod 🐙'
gas_price = { price = 0.001, denom = 'uakt' }
max_gas = 2000000
clock_drift ='7200s'
trusting_period ='14days'
trust_threshold = { numerator = '1', denominator = '3' }

[[chains]]
id = 'sentinelhub-2'
rpc_addr = 'http://10.10.51.16:26670'
grpc_addr = 'http://10.10.51.16:26672'
websocket_addr = 'ws://sentinelhub0:26670/websocket'
rpc_timeout = '8s'
account_prefix = 'sent'
key_name = 'aw1'
store_prefix = 'ibc'
memo_prefix = 'Connect the Interchain. Stake with Cephalopod 🐙'
gas_price = { price = 0.01, denom = 'udvpn' }
max_gas = 2000000
max_msg_num = 15
clock_drift = '7200s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }

[[chains]]
id = 'crypto-org-chain-mainnet-1'
rpc_addr = 'http://crypto0:26600'
grpc_addr = 'http://crypto0:26602'
websocket_addr = 'ws://crypto0:26600/websocket'
rpc_timeout = '8s'
account_prefix = 'cro'
key_name = 'aw1'
store_prefix = 'ibc'
memo_prefix = 'Connect the Interchain. Stake with Cephalopod 🐙'
gas_price  =  { price  =  0.1, denom  =  'basecro' }
max_gas = 1200000
max_msg_num = 15
max_tx_size = 450000
clock_drift = '7200s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }

[[chains]]
id = 'regen-1'
rpc_addr = 'http://regen1:26600'
grpc_addr = 'http://regen1:26602'
websocket_addr = 'ws://regen1:26600/websocket'
rpc_timeout = '8s'
account_prefix = 'regen'
key_name = 'aw1'
store_prefix = 'ibc'
memo_prefix = 'Connect the Interchain. Stake with Cephalopod 🐙'
gas_price  =  { price  =  0.1, denom  =  'uregen' }
max_gas = 2000000
max_msg_num = 15
max_tx_size = 180000
clock_drift = '7200s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }

[[chains]]
id = 'core-1'
rpc_addr = 'http://core-archive:26600'
grpc_addr = 'http://core-archive:26602'
websocket_addr = 'ws://core0:26600/websocket'
rpc_timeout = '8s'
account_prefix = 'persistence'
key_name = 'aw1'
store_prefix = 'ibc'
memo_prefix = 'Connect the Interchain. Stake with Cephalopod 🐙'
gas_price  =  { price  =  0.001, denom  =  'uxprt' }
max_gas = 2000000
max_msg_num = 15
max_tx_size = 180000
clock_drift = '7200s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }

[[chains]]
id = 'irishub-1'
rpc_addr = 'http://10.10.51.16:26650'
grpc_addr = 'http://10.10.51.16:26652'
websocket_addr = 'ws://irishub0:26600/websocket'
rpc_timeout = '8s'
account_prefix = 'iaa'
key_name = 'aw1'
store_prefix = 'ibc'
memo_prefix = 'Connect the Interchain. Stake with Cephalopod 🐙'
gas_price  =  { price  =  1, denom  =  'uiris' }
max_gas = 5000000
max_msg_num = 50
max_tx_size = 1800000
clock_drift = '7200s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }

[[chains]]
id = 'iov-mainnet-ibc'
rpc_addr = 'http://iov0:26600'
grpc_addr = 'http://iov0:26602'
websocket_addr = 'ws://iov0:26600/websocket'
rpc_timeout = '8s'
account_prefix = 'star'
key_name = 'aw1'
store_prefix = 'ibc'
memo_prefix = 'Connect the Interchain. Stake with Cephalopod 🐙'
gas_price  =  { price  =  0.1, denom  =  'uiov' }
max_gas = 5000000
max_msg_num = 15
max_tx_size = 450000
clock_drift = '7200s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }

[[chains]]
id = 'impacthub-3'
rpc_addr = 'http://impacthub0:26600'
grpc_addr = 'http://impacthub0:26602'
websocket_addr = 'ws://impacthub0:26600/websocket'
rpc_timeout = '8s'
account_prefix = 'ixo'
key_name = 'aw1'
store_prefix = 'ibc'
memo_prefix = 'Connect the Interchain. Stake with Cephalopod 🐙'
gas_price = { price = 0.01, denom = 'uixo' }
max_gas = 5000000
max_msg_num = 15
max_tx_size = 180000
clock_drift = '7200s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }

[[chains]]
id = 'juno-1'
rpc_addr = 'http://juno0.cec:26600'
grpc_addr = 'http://juno0.cec:26602'
websocket_addr = 'ws://juno0.cec:26600/websocket'
rpc_timeout = '8s'
account_prefix = 'juno'
key_name = 'aw1'
store_prefix = 'ibc'
memo_prefix = 'Connect the Interchain. Stake with Cephalopod 🐙'
gas_price  =  { price  =  0.001, denom  =  'ujuno' }
max_gas = 5000000
max_msg_num = 15
max_tx_size = 450000
clock_drift = '7200s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }

[[chains]]
id = 'osmosis-1'
rpc_addr = 'http://10.10.51.77:26630'
grpc_addr = 'http://10.10.51.77:26632'
websocket_addr = 'ws://osmosis1:26670/websocket'
rpc_timeout = '8s'
account_prefix = 'osmo'
key_name = 'aw1'
store_prefix = 'ibc'
memo_prefix = 'Connect the Interchain. Stake with Cephalopod 🐙'
gas_price  =  { price  =  0.1, denom  =  'uosmo' }
max_gas = 19000000
max_msg_num = 50
clock_drift = '7200s'
trusting_period = '10days'
trust_threshold = { numerator = '1', denominator = '3' }

[[chains]]
id = 'sifchain-1'
rpc_addr = 'http://sif0:26600'
grpc_addr = 'http://sif0:26602'
websocket_addr = 'ws://sif0:26600/websocket'
rpc_timeout = '8s'
account_prefix = 'sif'
key_name = 'aw1'
store_prefix = 'ibc'
memo_prefix = 'Connect the Interchain. Stake with Cephalopod 🐙'
gas_price = { price = 100000000000, denom = 'rowan' }
max_gas = 5000000
max_msg_num = 15
max_tx_size = 180000
max_block_time = '3s'
clock_drift = '1s'
trusting_period = '14days'

[[chains]]
id = 'emoney-3'
rpc_addr = 'http://emoney0:26600'
grpc_addr = 'http://emoney0:26602'
websocket_addr = 'ws://emoney0:26600/websocket'
rpc_timeout = '8s'
account_prefix = 'emoney'
key_name = 'aw1'
store_prefix = 'ibc'
max_tx_size = 180000
max_msg_num = 15
memo_prefix = 'Connect the Interchain. Stake with Cephalopod 🐙'
gas_price = { price = 0.1, denom = 'ungm' }
max_gas = 5000000
clock_drift = '70s'
trusting_period = '10days'
trust_threshold = { numerator = '1', denominator = '3' }

[[chains]]
id = 'gravity-bridge-3'
rpc_addr = 'http://gravity0:26600'
grpc_addr = 'http://gravity0:26602'
websocket_addr = 'ws://gravity0:26600/websocket'
rpc_timeout = '8s'
account_prefix = 'gravity'
key_name = 'aw1'
store_prefix = 'ibc'
memo_prefix = 'Connect the Interchain. Stake with Cephalopod 🐙'
gas_price  =  { price  =  0.001, denom  =  'ugraviton' }
max_gas = 19000000
max_msg_num = 8
clock_drift = '7200s'
trusting_period = '10days'
trust_threshold = { numerator = '1', denominator = '3' }


[[chains]]
id = 'columbus-5'
rpc_addr = 'http://terra0:26600'
grpc_addr = 'http://terra0:26602'
websocket_addr = 'ws://terra0:26600/websocket'
rpc_timeout = '8s'
account_prefix = 'terra'
key_name = 'aw1'
store_prefix = 'ibc'
memo_prefix = 'Connect the Interchain. Stake with Cephalopod 🐙'
gas_price = { price = 1.25, denom = 'usek' }
max_gas = 1000000
max_msg_num = 50
max_tx_size = 650000
clock_drift = '1s'
max_block_time = '3s'
trusting_period = '57600s'
trust_threshold = { numerator = '1', denominator = '3' }
