[global]
log_level = 'debug'

[mode]
[mode.clients]
enabled = false

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true

[[chains]]
id = 'cosmoshub-4'
rpc_addr = 'http://cosmoshub-archive:26600'
grpc_addr = 'http://cosmoshub-archive:26602'
websocket_addr = 'ws://cosmoshub1:26600/websocket'
rpc_timeout = '8s'
account_prefix = 'cosmos'
key_name = 'aw1'
store_prefix = 'ibc'
memo_prefix = 'Connect the Interchain. Stake with Cephalopod 🐙'
gas_price  =  { price  =  0.0002, denom  =  'uatom' }
max_gas = 3000000
max_msg_num = 15
max_tx_size = 180000
clock_drift = '7200s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }

[[chains]]
id ='akashnet-2'
rpc_addr ='http://10.10.51.16:26630'
grpc_addr ='http://10.10.51.16:26632'
websocket_addr ='ws://akashnet1:26600/websocket'
rpc_timeout ='8s'
account_prefix ='akash'
key_name ='aw1'
store_prefix ='ibc'
memo_prefix = 'Connect the Interchain. Stake with Cephalopod 🐙'
gas_price = { price = 0.001, denom = 'uakt' }
max_gas = 2000000
clock_drift ='7200s'
trusting_period ='14days'
trust_threshold = { numerator = '1', denominator = '3' }


[[chains]]
id = 'crypto-org-chain-mainnet-1'
rpc_addr = 'http://crypto0:26600'
grpc_addr = 'http://crypto0:26602'
websocket_addr = 'ws://crypto0:26600/websocket'
rpc_timeout = '8s'
account_prefix = 'cro'
key_name = 'aw1'
store_prefix = 'ibc'
memo_prefix = 'Connect the Interchain. Stake with Cephalopod 🐙'
gas_price  =  { price  =  0.1, denom  =  'basecro' }
max_gas = 1200000
max_msg_num = 15
max_tx_size = 450000
clock_drift = '7200s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }

[[chains]]
id = 'regen-1'
rpc_addr = 'http://regen1:26600'
grpc_addr = 'http://regen1:26602'
websocket_addr = 'ws://regen1:26600/websocket'
rpc_timeout = '8s'
account_prefix = 'regen'
key_name = 'aw1'
store_prefix = 'ibc'
memo_prefix = 'Connect the Interchain. Stake with Cephalopod 🐙'
gas_price  =  { price  =  0.1, denom  =  'uregen' }
max_gas = 2000000
max_msg_num = 15
max_tx_size = 180000
clock_drift = '7200s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }


[[chains]]
id = 'impacthub-3'
rpc_addr = 'http://impacthub0:26600'
grpc_addr = 'http://impacthub0:26602'
websocket_addr = 'ws://impacthub0:26600/websocket'
rpc_timeout = '8s'
account_prefix = 'ixo'
key_name = 'aw1'
store_prefix = 'ibc'
memo_prefix = 'Connect the Interchain. Stake with Cephalopod 🐙'
gas_price = { price = 0.01, denom = 'uixo' }
max_gas = 5000000
max_msg_num = 15
max_tx_size = 180000
clock_drift = '7200s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }

[[chains]]
id = 'juno-1'
rpc_addr = 'http://juno0.cec:26600'
grpc_addr = 'http://juno0.cec:26602'
websocket_addr = 'ws://juno0.cec:26600/websocket'
rpc_timeout = '8s'
account_prefix = 'juno'
key_name = 'aw1'
store_prefix = 'ibc'
memo_prefix = 'Connect the Interchain. Stake with Cephalopod 🐙'
gas_price  =  { price  =  0.001, denom  =  'ujuno' }
max_gas = 5000000
max_msg_num = 15
max_tx_size = 450000
clock_drift = '7200s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }

[[chains]]
id = 'osmosis-1'
rpc_addr = 'http://10.10.51.174:26670'
grpc_addr = 'http://10.10.51.174:26672'
websocket_addr = 'ws://osmosis1:26670/websocket'
rpc_timeout = '8s'
account_prefix = 'osmo'
key_name = 'aw1'
store_prefix = 'ibc'
memo_prefix = 'Connect the Interchain. Stake with Cephalopod 🐙'
gas_price  =  { price  =  0.1, denom  =  'uosmo' }
max_gas = 19000000
max_msg_num = 100
clock_drift = '7200s'
trusting_period = '10days'
trust_threshold = { numerator = '1', denominator = '3' }