# Tendermint KMS configuration file

## Chain Configuration

### Regen Network

#[[chain]]
#id = "regen-1"
#key_format = { type = "bech32", account_key_prefix = "regenpub", consensus_key_prefix = "regenvalconspub" }
#state_file = "/home/tmkms/state/regen-1-consensus.json"

### Osmosis Network

#[[chain]]
#id = "osmosis-1"
#key_format = { type = "bech32", account_key_prefix = "osmopub", consensus_key_prefix = "osmovalconspub" }
#state_file = "/home/tmkms/state/osmosis-1-consensus.json"

### Cosmos Hub

#[[chain]]
#id = "cosmoshub-4"
#key_format = { type = "bech32", account_key_prefix = "cosmospub", consensus_key_prefix = "cosmosvalconspub" }
#state_file = "/home/tmkms/state/cosmoshub-4-consensus.json"

### Impacthub

[[chain]]
id = "impacthub-3"
key_format = { type = "bech32", account_key_prefix = "ixopub", consensus_key_prefix = "ixovalconspub" }
state_file = "/home/tmkms/state/impacthub-3-consensus.json"


## Signing Provider Configuration

### YubiHSM2 Provider Configuration

[[providers.yubihsm]]
adapter = { type = "usb" }
auth = { key = 4, password_file = "/home/tmkms/secrets/validator-password" }
serial_number = "0008085303" # serial number of a specific YubiHSM to connect to (optional)
keys = [
#    { key = 1, type = "consensus", chain_ids = ["cosmoshub-4"] }, 
#    { key = 2, type = "consensus", chain_ids = ["regen-1"] }, 
    { key = 3, type = "consensus", chain_ids = ["impacthub-3"] }, 
#    { key = 4, type = "consensus", chain_ids = ["osmosis-1"] }, 
]

## Validator Configuration

[[validator]]
chain_id = "impacthub-3"
addr = "10.10.10.100:26000"
secret_key = "/home/tmkms/secrets/kms-identity.key"
protocol_version = "v0.34"
reconnect = true

#[[validator]]
#chain_id = "cosmoshub-4"
#addr = "10.10.10.101:27000"
#secret_key = "/home/tmkms/secrets/kms-identity.key"
#protocol_version = "v0.34"
#reconnect = true

#[[validator]]
#chain_id = "regen-1"
#addr = "10.10.10.101:28000"
#secret_key = "/home/tmkms/secrets/kms-identity.key"
#protocol_version = "v0.34"
#reconnect = true

#[[validator]]
#chain_id = "osmosis-1"
#addr = "10.10.10.101:29000"
#secret_key = "/home/tmkms/secrets/kms-identity.key"
#protocol_version = "v0.34"
#reconnect = true
