[global]
strategy = 'packets'
log_level = 'debug'
#tx_confirmation = true


[[chains]]
id='cosmoshub-4'
rpc_addr='http://10.10.51.186:26657' # cosmoshub1
grpc_addr='http://10.10.51.186:9090'
websocket_addr='ws://10.10.51.186:26657/websocket'
rpc_timeout='30s'
account_prefix='cosmos'
key_name='aw4'
store_prefix='ibc'
gas_price = { price = 0.0001, denom = 'uatom' }
max_gas=5000000
max_msg_num=15
max_tx_size=180000
clock_drift='7200s'
trusting_period='14days'

[chains.trust_threshold]
numerator='1'
denominator='3'


[[chains]]
id='akashnet-2'
rpc_addr='http://10.10.51.79:26657' # akashnet0
grpc_addr='http://10.10.51.79:9090'
websocket_addr='ws://10.10.51.79:26657/websocket'
rpc_timeout='30s'
account_prefix='akash'
key_name='aw4'
store_prefix='ibc'
gas_price = { price = 0.001, denom = 'uakt' }
max_gas=1000000
clock_drift='7200s'
trusting_period='14days'

[chains.trust_threshold]
numerator='1'
denominator='3'


[[chains]]
id='sentinelhub-2'
rpc_addr='http://10.10.51.47:26657' # sentinelhub0
grpc_addr='http://10.10.51.47:9090'
websocket_addr='ws://10.10.51.47:26657/websocket'
rpc_timeout='30s'
account_prefix='sent'
key_name='aw4'
store_prefix='ibc'
gas_price = { price = 0.05, denom = 'udvpn' }
max_gas=1000000
max_msg_num=15
clock_drift='7200s'
trusting_period='14days'

[chains.trust_threshold]
numerator='1'
denominator='3'


[[chains]]
id='crypto-org-chain-mainnet-1'
rpc_addr='http://10.10.51.95:26657' # crypto1
grpc_addr='http://10.10.51.95:9090'
websocket_addr='ws://10.10.51.95:26657/websocket'
rpc_timeout='30s'
account_prefix='cro'
key_name='aw4'
store_prefix='ibc'
gas_price = { price = 0.03, denom = 'basecro' }
max_gas=1200000
max_msg_num=15
max_tx_size=450000
clock_drift='7200s'
trusting_period='14days'

[chains.trust_threshold]
numerator='1'
denominator='3'


[[chains]]
id='regen-1'
rpc_addr='http://10.10.51.245:26657'
grpc_addr='http://10.10.51.245:9090'
websocket_addr='ws://10.10.51.245:26657/websocket'
rpc_timeout='30s'
account_prefix='regen'
key_name='aw4'
store_prefix='ibc'
gas_price = { price = 0.02, denom = 'uregen' }
max_gas=800000
max_msg_num=15
max_tx_size=180000
clock_drift='7200s'
trusting_period='14days'

[chains.trust_threshold]
numerator='1'
denominator='3'


[[chains]]
id='irishub-1'
rpc_addr='http://10.10.51.58:26657' # irishub0
grpc_addr='http://10.10.51.58:9090'
websocket_addr='ws://10.10.51.58:26657/websocket'
rpc_timeout='30s'
account_prefix='iaa'
key_name='aw4'
store_prefix='ibc'
gas_price = { price = 0.005, denom = 'uiris' }
max_gas=800000
max_tx_size=1800000
clock_drift='7200s'
trusting_period='14days'

[chains.trust_threshold]
numerator='1'
denominator='3'


[[chains]]
id='core-1'
rpc_addr='http://10.10.51.84:26657' # core0
grpc_addr='http://10.10.51.84:9090'
websocket_addr='ws://10.10.51.84:26657/websocket'
rpc_timeout='30s'
account_prefix='persistence'
key_name='aw4'
store_prefix='ibc'
gas_price = { price = 0.001, denom = 'uxprt' }
max_gas=1000000
max_tx_size=180000
clock_drift='7200s'
trusting_period='14days'

[chains.trust_threshold]
numerator='1'
denominator='3'


[[chains]]
id='sifchain-1'
rpc_addr='http://sif0.cec:26657'
grpc_addr='http://sif0.cec:9090'
websocket_addr='ws://sif0.cec:26657/websocket'
rpc_timeout='30s'
account_prefix='sif'
key_name='aw4'
store_prefix='ibc'
gas_price = { price = 1000000000000, denom = 'rowan' }
max_gas=2500000
max_msg_num=15
max_tx_size=180000
clock_drift='7200s'
trusting_period='14days'

[chains.trust_threshold]
numerator='1'
denominator='3'


[[chains]]
id='juno-1'
rpc_addr='http://juno0:26657'
grpc_addr='http://juno0:9090'
websocket_addr='ws://juno0:26657/websocket'
rpc_timeout='8s'
account_prefix='juno'
key_name='aw2'
store_prefix='ibc'
gas_price = { price = 0.02, denom = 'ujuno' }
max_gas=1000000
max_msg_num=15
max_tx_size=450000
clock_drift='7200s'
trusting_period='14days'

[chains.trust_threshold]
numerator='1'
denominator='3'


[[chains]]
id='impacthub-3'
rpc_addr='http://impacthub0:26657'
grpc_addr='http://impacthub0:9090'
websocket_addr='ws://impacthub0:26657/websocket'
rpc_timeout='8s'
account_prefix='ixo'
key_name='aw3'
store_prefix='ibc'
gas_price = { price = 0.0001, denom = 'uixo' }
max_gas=1500000
max_msg_num=15
max_tx_size=180000
clock_drift='7200s'
trusting_period='14days'

[chains.trust_threshold]
numerator='1'
denominator='3'

[[chains]]
id='osmosis-1'
rpc_addr='http://10.10.51.169:26657' # node: osmosis1
grpc_addr='http://10.10.51.169:9090'
websocket_addr='ws://10.10.51.169:26657/websocket'
rpc_timeout='30s'
account_prefix='osmo'
key_name='aw4'
store_prefix='ibc'
gas_price = { price = 0.001, denom = 'uosmo' }
max_gas=8000000
max_msg_num=8
clock_drift='7200s'
trusting_period='8days'

[chains.trust_threshold]
numerator='1'
denominator='3'
