[global]
strategy = 'packets'
log_level = 'debug'
filter = true
clear_packets_interval = 20
tx_confirmation = true


[[chains]]
id='cosmoshub-4'
rpc_addr='http://cosmoshub1:26657'
grpc_addr='http://cosmoshub1:9090'
websocket_addr='ws://cosmoshub1:26657/websocket'
rpc_timeout='8s'
account_prefix='cosmos'
key_name='aw4'
store_prefix='ibc'
gas_price = { price = 0.0001, denom = 'uatom' }
max_gas=5000000
max_msg_num=15
max_tx_size=180000
clock_drift='7200s'
trusting_period='14days'

[chains.packet_filter]
policy = 'allow'
list = [['transfer', 'channel-192']]

[chains.trust_threshold]
numerator='1'
denominator='3'


[[chains]]
id='akashnet-2'
rpc_addr='http://10.10.10.103:31904' # archive-node
grpc_addr='http://10.10.10.103:26703' 
#rpc_addr='http://akashnet0:26657' # akashnet0
#grpc_addr='http://akashnet0:9090'
websocket_addr='ws://akashnet0:26657/websocket'
rpc_timeout='8s'
account_prefix='akash'
key_name='aw4'
store_prefix='ibc'
gas_price = { price = 0.001, denom = 'uakt' }
max_gas=1000000
clock_drift='7200s'
trusting_period='14days'

[chains.packet_filter]
policy = 'allow'
list = [['transfer', 'channel-24']]

[chains.trust_threshold]
numerator='1'
denominator='3'


[[chains]]
id='sentinelhub-2'
rpc_addr='http://10.10.51.47:26657' # sentinelhub0
grpc_addr='http://10.10.51.47:9090'
websocket_addr='ws://10.10.51.47:26657/websocket'
rpc_timeout='8s'
account_prefix='sent'
key_name='aw4'
store_prefix='ibc'
gas_price = { price = 0.05, denom = 'udvpn' }
max_gas=1000000
max_msg_num=15
clock_drift='7200s'
trusting_period='14days'

[chains.packet_filter]
policy = 'allow'
list = [['transfer', 'channel-36']]

[chains.trust_threshold]
numerator='1'
denominator='3'


[[chains]]
id='crypto-org-chain-mainnet-1'
rpc_addr='http://10.10.51.95:26657' # crypto1
grpc_addr='http://10.10.51.95:9090'
websocket_addr='ws://10.10.51.95:26657/websocket'
rpc_timeout='8s'
account_prefix='cro'
key_name='aw4'
store_prefix='ibc'
gas_price = { price = 0.1, denom = 'basecro' }
max_gas=2000000
max_msg_num=15
max_tx_size=450000
clock_drift='7200s'
trusting_period='14days'

[chains.packet_filter]
policy = 'allow'
list = [['transfer', 'channel-33']]

[chains.trust_threshold]
numerator='1'
denominator='3'


[[chains]]
id='regen-1'
rpc_addr='http://10.10.51.245:26657'
grpc_addr='http://10.10.51.245:9090'
websocket_addr='ws://10.10.51.245:26657/websocket'
rpc_timeout='8s'
account_prefix='regen'
key_name='aw4'
store_prefix='ibc'
gas_price = { price = 0.02, denom = 'uregen' }
max_gas=800000
max_msg_num=15
max_tx_size=180000
clock_drift='7200s'
trusting_period='14days'

[chains.packet_filter]
policy = 'allow'
list = [['transfer', 'channel-28']]

[chains.trust_threshold]
numerator='1'
denominator='3'


[[chains]]
id='irishub-1'
rpc_addr='http://10.10.51.58:26657' # irishub0
grpc_addr='http://10.10.51.58:9090'
websocket_addr='ws://10.10.51.58:26657/websocket'
rpc_timeout='8s'
account_prefix='iaa'
key_name='aw4'
store_prefix='ibc'
gas_price = { price = 0.005, denom = 'uiris' }
max_gas=800000
max_tx_size=1800000
clock_drift='7200s'
trusting_period='14days'

[chains.packet_filter]
policy = 'allow'
list = [['transfer', 'channel-19']]

[chains.trust_threshold]
numerator='1'
denominator='3'


[[chains]]
id='core-1'
rpc_addr='http://10.10.51.84:26657' # core0
grpc_addr='http://10.10.51.84:9090'
websocket_addr='ws://10.10.51.84:26657/websocket'
rpc_timeout='8s'
account_prefix='persistence'
key_name='aw4'
store_prefix='ibc'
gas_price = { price = 0.001, denom = 'uxprt' }
max_gas=1000000
max_tx_size=180000
clock_drift='7200s'
trusting_period='14days'

[chains.packet_filter]
policy = 'allow'
list = [['transfer', 'channel-26']]

[chains.trust_threshold]
numerator='1'
denominator='3'


[[chains]]
id='sifchain-1'
rpc_addr='http://sif0:26657'
grpc_addr='http://sif0:9090'
websocket_addr='ws://sif0:26657/websocket'
rpc_timeout='8s'
account_prefix='sif'
key_name='aw4'
store_prefix='ibc'
gas_price = { price = 1000000000000, denom = 'rowan' }
max_gas=5000000
max_msg_num=15
max_tx_size=180000
clock_drift='7200s'
trusting_period='14days'

[chains.packet_filter]
policy = 'allow'
# cosmoshub, akash, crypto-org, iris, persistence, regen, sentinel, regen, osmosis, juno, ixo
list = [['transfer', 'channel-0'], ['transfer', 'channel-2'], ['transfer', 'channel-9'], ['transfer', 'channel-8'], ['transfer', 'channel-7'], ['transfer', 'channel-1'], ['transfer', 'channel-10'], ['transfer', 'channel-17'], ['transfer', 'channel-13'], ['transfer', 'channel-14'], ['transfer', 'channel-15']]

[chains.trust_threshold]
numerator='1'
denominator='3'


[[chains]]
id='juno-1'
rpc_addr='http://juno0:26657'
grpc_addr='http://juno0:9090'
websocket_addr='ws://juno0:26657/websocket'
rpc_timeout='8s'
account_prefix='juno'
key_name='aw4'
store_prefix='ibc'
gas_price = { price = 0.02, denom = 'ujuno' }
max_gas=1000000
max_msg_num=15
max_tx_size=450000
clock_drift='7200s'
trusting_period='14days'

[chains.packet_filter]
policy = 'allow'
list = [['transfer', 'channel-5']]

[chains.trust_threshold]
numerator='1'
denominator='3'


[[chains]]
id='impacthub-3'
rpc_addr='http://impacthub0:26657'
grpc_addr='http://impacthub0:9090'
websocket_addr='ws://impacthub0:26657/websocket'
rpc_timeout='8s'
account_prefix='ixo'
key_name='aw4'
store_prefix='ibc'
gas_price = { price = 0.0001, denom = 'uixo' }
max_gas=1500000
max_msg_num=15
max_tx_size=180000
clock_drift='7200s'
trusting_period='14days'

[chains.packet_filter]
policy = 'allow'
list = [['transfer', 'channel-11']]

[chains.trust_threshold]
numerator='1'
denominator='3'


[[chains]]
id='osmosis-1'
rpc_addr='http://osmosis1:26657'
grpc_addr='http://osmosis1:9090'
websocket_addr='ws://osmosis0:26657/websocket'
rpc_timeout='8s'
account_prefix='osmo'
key_name='aw4'
store_prefix='ibc'
gas_price = { price = 0.1, denom = 'uosmo' }
max_gas=8000000
max_msg_num=8
clock_drift='7200s'
trusting_period='8days'

[chains.packet_filter]
policy = 'allow'
list = [['transfer', 'channel-47']]

[chains.trust_threshold]
numerator='1'
denominator='3'


[[chains]]
id = 'columbus-5'
rpc_addr = 'http://terra0:26657'
grpc_addr = 'http://terra0:9090'
websocket_addr = 'ws://terra0:26657/websocket'
rpc_timeout = '8s'
account_prefix = 'terra'
key_name = 'aw4'
store_prefix = 'ibc'
gas_price = { price = 0.001, denom = 'uluna' }
max_gas = 2000000
clock_drift ='5s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }


[[chains]]
id='emoney-3'
rpc_addr='http://emoney0:26657'
grpc_addr='http://emoney0:9090'
websocket_addr='ws://emoney0:26657/websocket'
rpc_timeout='8s'
account_prefix='emoney'
key_name = 'aw4'
store_prefix='ibc'
max_tx_size=180000
max_msg_num=15
memo_prefix = 'Connect the Interchain. Stake with Cephalopod 🐙'
gas_price = { price = 0.1, denom = 'ungm' }
max_gas = 5000000
clock_drift='70s'
trusting_period='10days'
trust_threshold={ numerator = '1', denominator = '3' }

