[global]
strategy = 'packets'
log_level = 'debug'
filter = true
clear_packets_interval = 20

[rest]
enabled = true
host = '0.0.0.0'
port = 3000


[[chains]]
id='cosmoshub-4'
rpc_addr='http://10.10.51.86:26657' # cosmoshub0
grpc_addr='http://10.10.51.86:9090'
websocket_addr='ws://10.10.51.86:26657/websocket'
rpc_timeout='8s'
account_prefix='cosmos'
key_name='aw3'
store_prefix='ibc'
gas_price = { price = 0.0005, denom = 'uatom' }
max_gas=1100000
max_msg_num=15
max_tx_size=180000
clock_drift='7200s'
trusting_period='14days'

[chains.packet_filter]
policy = 'allow'
# [akash, crypto-org, iris, persistence, regen, sentinel]
list = [['transfer', 'channel-184'], ['transfer', 'channel-187'], ['transfer', 'channel-182'], ['transfer', 'channel-190'], ['transfer', 'channel-185'], ['transfer', 'channel-186']]

[chains.trust_threshold]
numerator='1'
denominator='3'


[[chains]]
id='akashnet-2'
rpc_addr='http://10.10.51.79:26657' # akashnet0
grpc_addr='http://10.10.51.79:9090'
websocket_addr='ws://10.10.51.79:26657/websocket'
rpc_timeout='8s'
account_prefix='akash'
key_name='aw3'
store_prefix='ibc'
gas_price = { price = 0.005, denom = 'uakt' }
max_gas=1500000
clock_drift='7200s'
trusting_period='14days'

[chains.packet_filter]
policy = 'allow'
# [cosmos-hub, crypto-org, iris, persistence, regen, sentinel, osmosis]
list = [['transfer', 'channel-17'], ['transfer', 'channel-18'], ['transfer', 'channel-16'], ['transfer', 'channel-20'], ['transfer', 'channel-21'], ['transfer', 'channel-22'], ['transfer', 'channel-9']]

[chains.trust_threshold]
numerator='1'
denominator='3'


[[chains]]
id='sentinelhub-2'
rpc_addr='http://10.10.51.47:26657' # sentinelhub0
grpc_addr='http://10.10.51.47:9090'
websocket_addr='ws://10.10.51.47:26657/websocket'
rpc_timeout='8s'
account_prefix='sent'
key_name='aw3'
store_prefix='ibc'
gas_price = { price = 0.05, denom = 'udvpn' }
max_gas=1000000
max_msg_num=15
clock_drift='7200s'
trusting_period='14days'

[chains.packet_filter]
policy = 'allow'
# [akash, cosmos-hub, crypto-org, iris, persistence, regen]
list = [['transfer', 'channel-10'], ['transfer', 'channel-12'], ['transfer', 'channel-13'], ['transfer', 'channel-9'], ['transfer', 'channel-15'], ['transfer', 'channel-11']]

[chains.trust_threshold]
numerator='1'
denominator='3'


[[chains]]
id='crypto-org-chain-mainnet-1'
rpc_addr='http://10.10.51.95:26657' # crypto0
grpc_addr='http://10.10.51.95:9090'
websocket_addr='ws://10.10.51.95:26657/websocket'
rpc_timeout='8s'
account_prefix='cro'
key_name='aw3'
store_prefix='ibc'
gas_price = { price = 0.03, denom = 'basecro' }
max_gas=1200000
max_msg_num=15
max_tx_size=450000
clock_drift='7200s'
trusting_period='14days'

[chains.packet_filter]
policy = 'allow'
# [akash, cosmos-hub, iris, persistence, regen, sentinel]
list = [['transfer', 'channel-24'], ['transfer', 'channel-27'], ['transfer', 'channel-23'], ['transfer', 'channel-29'], ['transfer', 'channel-25'], ['transfer', 'channel-26']]

[chains.trust_threshold]
numerator='1'
denominator='3'


[[chains]]
id='regen-1'
rpc_addr='http://10.10.51.245:26657'
grpc_addr='http://10.10.51.245:9090'
websocket_addr='ws://10.10.51.245:26657/websocket'
rpc_timeout='8s'
account_prefix='regen'
key_name='aw3'
store_prefix='ibc'
gas_price = { price = 0.02, denom = 'uregen' }
max_gas=800000
max_msg_num=15
max_tx_size=180000
clock_drift='7200s'
trusting_period='14days'

[chains.packet_filter]
policy = 'allow'
# [akash, cosmos-hub, crypto-org, iris, persistence, sentinel]
list = [['transfer', 'channel-10'], ['transfer', 'channel-11'], ['transfer', 'channel-12'], ['transfer', 'channel-9'], ['transfer', 'channel-14'], ['transfer', 'channel-15']]

[chains.trust_threshold]
numerator='1'
denominator='3'


[[chains]]
id='irishub-1'
rpc_addr='http://10.10.51.58:26657' # irishub0
grpc_addr='http://10.10.51.58:9090'
websocket_addr='ws://10.10.51.58:26657/websocket'
rpc_timeout='8s'
account_prefix='iaa'
key_name='aw3'
store_prefix='ibc'
gas_price = { price = 0.005, denom = 'uiris' }
max_gas=800000
max_tx_size=1800000
clock_drift='7200s'
trusting_period='14days'

[chains.packet_filter]
policy = 'allow'
# [akash, cosmos-hub, crypto-org, persistence, regen, sentinel]
list = [['transfer', 'channel-11'], ['transfer', 'channel-12'], ['transfer', 'channel-13'], ['transfer', 'channel-15'], ['transfer', 'channel-16'], ['transfer', 'channel-17']]

[chains.trust_threshold]
numerator='1'
denominator='3'


[[chains]]
id='core-1'
rpc_addr='http://10.10.51.84:26657' # core0
grpc_addr='http://10.10.51.84:9090'
websocket_addr='ws://10.10.51.84:26657/websocket'
rpc_timeout='8s'
account_prefix='persistence'
key_name='aw3'
store_prefix='ibc'
gas_price = { price = 0.002, denom = 'uxprt' }
max_gas=1000000
max_tx_size=180000
clock_drift='7200s'
trusting_period='14days'

[chains.packet_filter]
policy = 'allow'
# [akash, cosmos-hub, crypto-org, iris, regen, sentinel]
list = [['transfer', 'channel-20'], ['transfer', 'channel-24'], ['transfer', 'channel-23'], ['transfer', 'channel-19'], ['transfer', 'channel-21'], ['transfer', 'channel-22']]

[chains.trust_threshold]
numerator='1'
denominator='3'

#[[chains]]
#id='osmosis-1'
#rpc_addr='http://10.10.51.169:26657' # node: osmosis1
#grpc_addr='http://10.10.51.169:9090'
#websocket_addr='ws://10.10.51.169:26657/websocket'
#rpc_timeout='8s'
#account_prefix='osmo'
#key_name='aw3'
#store_prefix='ibc'
#gas_price = { price = 0.001, denom = 'uosmo' }
#max_gas=5000000
#max_msg_num=8
#clock_drift='7200s'
#trusting_period='14days'

#[chains.packet_filter]
#policy = 'allow'
## akash, sentinel, crypto, regen, iris, iov, persistence
#list = [['transfer', 'channel-1'],['transfer', 'channel-2'],['transfer', 'channel-5'],['transfer', 'channel-8'],['transfer', 'channel-6'],['transfer', 'channel-15'],['transfer', 'channel-4']]

#[chains.trust_threshold]
#numerator='1'
#denominator='3'
