[global]
strategy = 'packets'
log_level = 'debug'
filter = true
clear_packets_interval = 100

[[chains]]
id='akashnet-2'
rpc_addr='http://10.10.51.69:26657'
grpc_addr='http://10.10.51.69:9090'
websocket_addr='ws://10.10.51.69:26657/websocket'
rpc_timeout='8s'
account_prefix='akash'
key_name='gdex-akash'
store_prefix='ibc'
gas_price = { price = 0.01, denom = 'uakt' }
max_gas=2000000
clock_drift='7200s'
trusting_period='14days'

[chains.packet_filter]
policy = 'allow'
# [cosmos-hub, crypto-org, iris, persistence, regen, sentinel]
list = [['transfer', 'channel-17'], ['transfer', 'channel-18'], ['transfer', 'channel-16'], ['transfer', 'channel-20'], ['transfer', 'channel-21'], ['transfer', 'channel-22']]

[chains.trust_threshold]
numerator='1'
denominator='3'

[[chains]]
id='cosmoshub-4'
rpc_addr='http://10.10.51.186:26657'
grpc_addr='http://10.10.51.186:9090'
websocket_addr='ws://10.10.51.186:26657/websocket'
rpc_timeout='8s'
account_prefix='cosmos'
key_name='gdex-hub'
store_prefix='ibc'
gas_price = { price = 0.02, denom = 'uatom' }
max_gas=5000000
max_msg_num=15
clock_drift='7200s'
trusting_period='14days'

[chains.packet_filter]
policy = 'allow'
# [akash, crypto-org, iris, persistence, regen, sentinel]
list = [['transfer', 'channel-184'], ['transfer', 'channel-187'], ['transfer', 'channel-182'], ['transfer', 'channel-190'], ['transfer', 'channel-185'], ['transfer', 'channel-186']]

[chains.trust_threshold]
numerator='1'
denominator='3'

[[chains]]
id='crypto-org-chain-mainnet-1'
rpc_addr='http://10.10.10.103:25790'
grpc_addr='http://10.10.51.76:31029'
websocket_addr='ws://10.10.51.76:25790/websocket'
rpc_timeout='8s'
account_prefix='cro'
key_name='gdex-crypto'
store_prefix='ibc'
gas_price = { price = 0.01, denom = 'basecro' }
max_gas=2000000
max_msg_num=15
max_tx_size=450000
clock_drift='7200s'
trusting_period='14days'

[chains.packet_filter]
policy = 'allow'
# [akash, cosmos-hub, iris, persistence, regen, sentinel]
list = [['transfer', 'channel-24'], ['transfer', 'channel-27'], ['transfer', 'channel-23'], ['transfer', 'channel-29'], ['transfer', 'channel-25'], ['transfer', 'channel-26']]

[chains.trust_threshold]
numerator='1'
denominator='3'

[[chains]]
id='irishub-1'
rpc_addr='http://10.10.51.66:26657'
grpc_addr='http://10.10.51.66:9090'
websocket_addr='ws://10.10.51.66:26657/websocket'
rpc_timeout='8s'
account_prefix='iaa'
key_name='gdex-irishub'
store_prefix='ibc'
gas_price = { price = 0.01, denom = 'uiris' }
max_gas=1500000
max_tx_size=1800000
clock_drift='7200s'
trusting_period='14days'

[chains.packet_filter]
policy = 'allow'
# [akash, cosmos-hub, crypto-org, persistence, regen, sentinel]
list = [['transfer', 'channel-11'], ['transfer', 'channel-12'], ['transfer', 'channel-13'], ['transfer', 'channel-15'], ['transfer', 'channel-16'], ['transfer', 'channel-17']]

[chains.trust_threshold]
numerator='1'
denominator='3'

[[chains]]
id='core-1'
rpc_addr='http://10.10.51.40:26657'
grpc_addr='http://10.10.51.40:9090'
websocket_addr='ws://10.10.51.40:26657/websocket'
rpc_timeout='8s'
account_prefix='persistence'
key_name='gdex-core'
store_prefix='ibc'
gas_price = { price = 0.01, denom = 'uxprt' }
max_gas=1000000
max_tx_size=180000
clock_drift='7200s'
trusting_period='14days'

[chains.packet_filter]
policy = 'allow'
# [akash, cosmos-hub, crypto-org, iris, regen, sentinel]
list = [['transfer', 'channel-20'], ['transfer', 'channel-24'], ['transfer', 'channel-23'], ['transfer', 'channel-19'], ['transfer', 'channel-21'], ['transfer', 'channel-22']]

[chains.trust_threshold]
numerator='1'
denominator='3'

[[chains]]
id='regen-1'
rpc_addr='http://10.10.51.245:26657'
grpc_addr='http://10.10.51.245:9090'
websocket_addr='ws://10.10.51.245:26657/websocket'
rpc_timeout='8s'
account_prefix='regen'
key_name='gdex-regen'
store_prefix='ibc'
gas_price = { price = 0.01, denom = 'uregen' }
max_gas=2000000
max_msg_num=15
max_tx_size=180000
clock_drift='7200s'
trusting_period='14days'

[chains.packet_filter]
policy = 'allow'
# [akash, cosmos-hub, crypto-org, iris, persistence, sentinel]
list = [['transfer', 'channel-10'], ['transfer', 'channel-11'], ['transfer', 'channel-12'], ['transfer', 'channel-9'], ['transfer', 'channel-14'], ['transfer', 'channel-15']]

[chains.trust_threshold]
numerator='1'
denominator='3'

[[chains]]
id='sentinelhub-2'
rpc_addr='http://10.10.10.103:28430'
grpc_addr='http://10.10.10.103:22837'
websocket_addr='ws://10.10.10.103:28430/websocket'
rpc_timeout='8s'
account_prefix='sent'
key_name='gdex-sentinel'
store_prefix='ibc'
gas_price = { price = 0.01, denom = 'udvpn' }
max_gas=2000000
max_msg_num=15
clock_drift='7200s'
trusting_period='14days'

[chains.packet_filter]
policy = 'allow'
# [akash, cosmos-hub, crypto-org, iris, persistence, regen]
list = [['transfer', 'channel-10'], ['transfer', 'channel-12'], ['transfer', 'channel-13'], ['transfer', 'channel-9'], ['transfer', 'channel-15'], ['transfer', 'channel-11']]

[chains.trust_threshold]
numerator='1'
denominator='3'
